### ISSUE TITLE
Create Heroku app

### ISSUE THREAD

**Issue by jacebrowning** [dwelling-place/red#1]
What would you like it to be?

**Comment by jacebrowning** [comment]
@brondsem Needs to create the app under the Dwelling Place Heroku account then add use as collaborators.

**Comment by AstraLuma** [comment]
Ummm... `dwelling-red` is fine.

**Comment by brondsem** [comment]
Integrating via https://github.com/dwelling-place/dwelling-place/issues/68 instead
